name: Change PR
on:
  pull_request:
    types:  [edited]
jobs:
  changePrBuild:
    if: github.event.action == 'edited' && !contains(github.event.pull_request.title, 'Draft:')
    name: PR ready for review
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: pmuraus/jira-ticket-transition-action@v1
        with:
          targetTransition: "In Review"
          sourceTransition: "In Progress"
          jiraBaseUrl: "inova-it.atlassian.net"
          jiraEmail: "hudson@inova.si"
          jiraToken: ${{secrets.JIRA_TOKEN}}
          githubToken: ${{secrets.GITHUB_TOKEN}}
