name: Documentation
on:
  workflow_run:
    workflows: ["Release build"]
    types:
      - completed  # Trigger when the develop pipeline completes
  workflow_dispatch:  # Allow manual runs

concurrency:
  group: docs-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_documentation:
    #if: ${{ github.event.workflow_run.conclusion == 'success' }}  # Only run if the develop pipeline was successful
    runs-on: "self-hosted-mac"
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive
        ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Validate Xcode version
      run: |
          echo ${XCODE_VERSION}
          XCODE_VERSION=$(/usr/bin/xcodebuild -version 2>/dev/null | head -1)
          echo ${XCODE_VERSION}
          if [ "$XCODE_VERSION" == "Xcode 16.0"  ]
          then
            echo "Version up to date"
          else
            echo "Wrong version"
            exit 1
          fi

    - name: Build documentation
      run: >
        rm -rf docs-out 
