name: Documentation
on:
  workflow_run:
    workflows: ["Release build"]
    types:
      - completed  # Trigger when the develop pipeline completes
  workflow_dispatch:  # Allow manual runs

concurrency:
  group: docs-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_documentation:
    #if: ${{ github.event.workflow_run.conclusion == 'success' }}  # Only run if the develop pipeline was successful
    runs-on: "self-hosted-mac"
    steps:
    - name: Validate Xcode version
      run: |
          echo ${XCODE_VERSION}
          XCODE_VERSION=$(/usr/bin/xcodebuild -version 2>/dev/null | head -1)
          echo ${XCODE_VERSION}
          if [ "$XCODE_VERSION" == "Xcode 16.0"  ]
          then
            echo "Version up to date"
          else
            echo "Wrong version"
            exit 1
          fi

    - name: Checkout package
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Generate Project (Tuist)
      run: |
          tuist clean
          tuist install
          tuist generate --no-open

    - name: Checkout gh-pages Branch
      uses: actions/checkout@v4
      with:
        ref: gh-pages
        path: docs-out

    - name: Build documentation
      run: >
        rm -rf docs-out/.git;
        rm -rf docs-out/main;
        git tag -l --sort=-v:refname | grep -e "\d\+\.\d\+.0" | tail -n +6 | xargs -I {} rm -rf {};

        for tag in $(echo "main"; git tag -l --sort=-v:refname | grep -e "\d\+\.\d\+.0" | head -6);
          do
            if [ -d "docs-out/$tag/data/documentation/tws-ios" ] 
            then 
              echo "✅ Documentation for "$tag" already exists.";
            else 
              echo "⏳ Generating documentation for TWS @ "$tag" release.";
              rm -rf "docs-out/$tag";
              git checkout .;
              git checkout "$tag";
              swift package \
                --allow-writing-to-directory docs-out/"$tag" \
                generate-documentation \
                --target TWSKit \
                --output-path docs-out/"$tag" \
                --transform-for-static-hosting \
                --hosting-base-path /tws-ios/"$tag" \
                && echo "✅ Documentation generated for TWS @ "$tag" release." \
                || echo "⚠️ Documentation skipped for TWS @ "$tag".";
            fi;
          done

    - name: Fix permissions
        run: 'sudo chown -R $USER docs-out'

    - name: Publish documentation to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.7
      with:
        branch: gh-pages
        folder: docs-out
        single-commit: true
